// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Scan.ModeState")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~M:TagHelperMethods.SharedMethods.#ctor(Skyline.DataMiner.DataMinerSolutions.ProcessAutomation.Manager.PaProfileLoadDomHelper,Skyline.DataMiner.Net.Apps.DataMinerObjectModel.DomHelper)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~M:TagHelperMethods.SharedMethods.GetManifests(Skyline.DataMiner.Net.Apps.DataMinerObjectModel.DomInstance)~System.Collections.Generic.List{TagHelperMethods.Manifest}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~M:TagHelperMethods.SharedMethods.GetScanRequestTitles(System.Collections.Generic.List{TagHelperMethods.Scan})~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~M:TagHelperMethods.SharedMethods.StartTAGChannelsProcess(TagHelperMethods.Scanner)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~M:TagHelperMethods.SharedMethods.TransitionToError(Skyline.DataMiner.DataMinerSolutions.ProcessAutomation.Manager.PaProfileLoadDomHelper,System.String)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~M:TagHelperMethods.TagRequest.#ctor")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.Delay")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.Descrambling")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.Encryption")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.Id")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.Kms")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.MonitoringLevel")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.Name")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.NotificationSet")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.Template")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Channel.ThresholdSet")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Layout.Id")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Layout.LayoutLayout")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Layout.Name")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Layout.Template")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Manifest.Name")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Manifest.Url")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Monitor.Id")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Monitor.Name")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Monitor.Template")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Multiviewer.Event")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Multiviewer.Layout")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scan.Action")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scan.AssetId")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scan.Interface")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scan.Name")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scan.Type")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scan.Url")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.Action")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.AssetId")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.Channels")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.InstanceId")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.ScanName")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.ScanType")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.SourceElement")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.SourceId")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.TagDevice")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.TagElement")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.Scanner.TagInterface")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.TagRequest.ChannelSets")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.TagRequest.MonitorRequests")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.TagRequest.MultiViewerRequests")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "member", Target = "~P:TagHelperMethods.TagRequest.ScanRequests")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Channel")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Layout")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Manifest")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.ModeState")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Monitor")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Multiviewer")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Scan")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Scan.ModeState")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Scanner")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.SharedMethods")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.TagRequest")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.TagRequest.TAGAction")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Channel")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Layout")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Monitor")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.Multiviewer")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1602:Enumeration items should be documented", Justification = "ignored", Scope = "type", Target = "~T:TagHelperMethods.ModeState")]
